export const fontsPoppins = {
  p1Thin: "Poppins_100Thin",
  p1ThinItalic: "Poppins_100Thin_Italic",
  p2ExtraLight: "Poppins_200ExtraLight",
  p2ExtraLightItalic: "Poppins_200ExtraLight_Italic",
  p3Light: "Poppins_300Light",
  p3LightItalic: "Poppins_300Light_Italic",
  p4Regular: "Poppins_400Regular",
  p4RegularItalic: "Poppins_400Regular_Italic",
  p5Medium: "Poppins_500Medium",
  p5MediumItalic: "Poppins_500Medium_Italic",
  p6SemiBold: "Poppins_600SemiBold",
  p6SemiBoldItalic: "Poppins_600SemiBold_Italic",
  p7Bold: "Poppins_700Bold",
  p7BoldItalic: "Poppins_700Bold_Italic",
  p8ExtraBold: "Poppins_800ExtraBold",
  p8ExtraBoldItalic: "Poppins_800ExtraBold_Italic",
  p9Black: "Poppins_900Black",
  p9BlackItalic: "Poppins_900Black_Italic",
};
